name: Django CI
on:
  pull_request:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Installation of dependencies(with poetry)
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install --with dev --sync
 
      - name: Running django tests with coverage
        run: poetry run pytest backend --cov=backend --cov-fail-under=70
